spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: dearment-service
          uri: lb://dearment-service
          predicates:
            - Path=/department/**
management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8060
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
